import BreakpointIndicator from "@/components/breakpoint-indicator";
import Navbar from "@/components/layout/navbar";
import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import localFont from "next/font/local";
import "../styles/globals.css";
import "../styles/ui.css";
import Footer from "@/components/layout/footer";

const mdn = localFont({
  src: "../fonts/MDN-Black.woff2",
  variable: "--font-mdn",
  weight: "900",
});

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolage.className} ${mdn.variable} dark relative scroll-smooth antialiased`}
      >
        <div vaul-drawer-wrapper="">
          <Navbar />
          {children}
          <Footer />
          <BreakpointIndicator />
        </div>
      </body>
    </html>
  );
}
